### ISSUE TITLE
Potential Feature - Overzoom for raster tiles

### ISSUE THREAD

**Issue by reyemtm** [consbio/mbtileserver#118]
Some map clients allow for overzoom on raster tiles, but not all, and in some scenarios there are special configuration options that need to happen when adding tiles. For my NodeJS project I implemented 3x ovezoom on raster tiles using a very simple expand and extract method. While creating raster tiles to zoom level 21 is ideal, it does take a lot of space. By only creating raster tiles to zoom level 20 and then applying a simple overzoom for zoom levels 21-23, satisfactory results can be achieved while reducing file size by 3-4x. I found that 3x overzoom is as far as you can go before the resolution starts to degrade. And ideally the tiles would be created to zoom level 20, but decent results can be achieved with lower zoom levels. 

I am not familiar with GO, but hope to move back to this script once Esri pushes their fix for not being able to print XYZ tiles at high zoom levels. Is there any interest in implementing an overzoom feature? You can see my efforts on the JavaScript overzoom implementation [here](https://github.com/reyemtm/wmts-server/blob/main/lib/overZoom.js).

**Comment by brendan-ward** [comment]
Thanks for the suggestion and example!

The main goal of `mbtileserver` is to provide an easy interface into existing tiles.  In the interest of keeping that simple and maintainable, I'd like to keep overzoom functionality or other things that derive other things from the tiles on the client side instead of implemented here.
