### ISSUE TITLE
Map page template issue

### ISSUE THREAD

**Issue by ka7eh** [consbio/mbtileserver#85]
Looks like `world_cities` example is using a different template from others, and causes the server to crash if you switch from that example to another one.

To reproduce, go to `world_cities` map page first (http://localhost:8080/services/world_cities/map) and then try another example (http://localhost:8080/services/geography-class-png/map), or the other way around.

Here's the error log:
`could not parse template asset "map": html/template: cannot Parse after Execute`

**Comment by brendan-ward** [comment]
Thanks for reporting @ka7eh 
I think we saw this before but didn't quite have enough information to reproduce it.  Now we do.

It's not immediately clear what is causing this.  It may be due to how we are getting templates from a pre-built binary.  https://godoc.org/github.com/shurcooL/httpfs/html/vfstemplate might be a better replacement for what we are doing there.

This would be obviated by #65

**Comment by sikmir** [comment]
> I think we saw this before but didn't quite have enough information to reproduce it. Now we do.

Yep, the same one #81.
