### ISSUE TITLE
Prebuilt executables with releases

### ISSUE THREAD

**Issue by kylebarron** [consbio/mbtileserver#86]
Hello! This looks like a great project.

I've seen many Go-based projects that have prebuilt executables with releases, that I think are autogenerated with Travis CI. I know you have a docker image, but it would be awesome to be able to easily download a built executable to a new cloud server without needing to install docker or Go.

Is this something you'd consider?

**Comment by brendan-ward** [comment]
@kylebarron this is a great idea, I'm all for it.  I won't be able to dig in immediately, but it seems like this should be fairly straightforward.

**Comment by brendan-ward** [comment]
@kylebarron first pass at this is now enabled using Github Actions: https://github.com/consbio/mbtileserver/releases/tag/v0.6.0

We're currently only generating binaries for linux (only Ubuntu 18.04 tested).  Does that hit the targets you needed?

We don't build MacOS binaries since newer versions of MacOS won't let them run without signing & notarization, which is out of scope here.

Since one of our underlying dependencies requires comping with C, I did not have a chance to get Windows builds working.  Go libraries / tools that don't need CGO have an easier time of this.

**Comment by kylebarron** [comment]
Awesome! I'll have to test it out. Unless someone else asks for it, I think Linux only is fine. (I'm guessing you don't expect problems between Linux distros). I would think most use cases would be on a small Linux cloud server (that's my use case). So I'm happy with that!

**Comment by sikmir** [comment]
@brendan-ward Could you please push 0.6.0 image to [Docker Hub](https://hub.docker.com/r/consbio/mbtileserver/tags) as well?

**Comment by brendan-ward** [comment]
@sikmir I discovered our builds were failing on Docker Hub due to out of memory errors.  I upgraded the Docker container to Go 1.14 which appears to have resolved this issue, and built `0.6.1` for this: https://hub.docker.com/layers/consbio/mbtileserver/0.6.1/images/sha256-b958683d358667e5aed695e0553c1ce929f5110980d247c87f87dc15f8be3d8e?context=repo

**Comment by brendan-ward** [comment]
First pass at this is complete.
