### ISSUE TITLE
Domain flag doesn't change Tile JSON

### ISSUE THREAD

**Issue by kylebarron** [consbio/mbtileserver#88]
Passing `--domain` doesn't seem to change the domain urls for me. Am I doing something wrong? I'd expect the urls to be changed to `http://example.com/services/...`.

To reproduce:
```
mbtileserver -d mbtiles -p 8891 --domain "example.com"
```

```
> curl localhost:8891/services/ | jq '.'
[
  {
    "imageType": "pbf",
    "url": "http://localhost:8891/services/california"
  },
  {
    "imageType": "pbf",
    "url": "http://localhost:8891/services/colorado"
  },
  {
    "imageType": "pbf",
    "url": "http://localhost:8891/services/new-mexico"
  },
  {
    "imageType": "pbf",
    "url": "http://localhost:8891/services/oregon"
  },
  {
    "imageType": "pbf",
    "url": "http://localhost:8891/services/washington"
  },
  {
    "imageType": "pbf",
    "url": "http://localhost:8891/services/british-columbia"
  }
]
```

**Comment by brendan-ward** [comment]
@kylebarron that is the result of poor documentation on our part.

The URLS are automatically constructed from the host of the incoming request, rather than set by the `--domain` flag.

The domain flag is really only used as part of setting up Auto TLS.

So - when you access this from localhost, it gives you back URLs on localhost.

If you access using a host mapped to that server, it gives you back those URLs.  For example, I mapped `example.local` in my `/etc/hosts` file to my machine `127.0.0.1`.  When I access it on those URLs, I get them back in the TileJSON:

```
[
    {
        "imageType":"pbf",
        "url":"http://example.local:8002/services/parcels_vt/calaveras"
    },
    ....
]
```

Sorry for the confusion there, I'll add a note to the README to clarify.

**Comment by kylebarron** [comment]
I think I fixed this by adding the correct Caddy proxy settings, so that host information from the original request is passed on to `mbtileserver`. But I still have one remaining domain/Tile JSON issue:

If I use anything other than `mbtileserver` for tls, then it appears that the urls in the Tile JSON stay as `http` and not `https`. For example, using Caddy for tls, and then requesting `https://mydomain.com/services/` responds with an _`http`_ url:
```
[{"imageType":"pbf","url":"http://mydomain.com/services/openmaptiles"}]
```
So when I try to load the map at `https://mydomain.com/services/openmaptiles/map`, it fails because the pages is loaded with https but the tiles are requested with http.

So essentially, is there any way to set the urls to automatically change to https?

**Comment by kylebarron** [comment]
I suppose a workaround for this is to put the `tiles` key directly in the `style.json` file, instead of pointing towards the hosted TileJSON, because then you can manually specify `https` required.

**Comment by brendan-ward** [comment]
@kylebarron sorry for the issues there, we likely aren't using the `scheme` where we should.  I'll try to get to a fix shortly.

**Comment by brendan-ward** [comment]
@kylebarron I think the problem was that your reverse proxy setup wasn't passing all the headers along that we needed to infer the`scheme` of the incoming request.

Using the `transparent` proxy directive in Caddy should fix that issue. 

Please see the updated README section for reverse proxy information; I tried to add enough information there to help future users avoid the issues you've had here.

I'm going to close this issue, since the server works as expected (I tested locally with a self-signed cert)  and hopefully should work properly with reverse proxies using the examples we provided.

Feel free to re-open if the issues were not resolved.

**Comment by kylebarron** [comment]
Thanks for this!

I was already using `transparent`, but I think the issue here was that my Cloudflare SSL settings were set to _Flexible_ instead of _Strict_, which apparently only uses encrypted traffic between the browser and Cloudflare. So Caddy was probably getting `http` traffic and passing that header on.

I fixed this by manually adding `https` headers to be added for `caddy` -> `mbtileserver`, so now my Caddy configuration looks like:
```
proxy / localhost:8000 {
    transparent
    header_upstream X-Forwarded-Proto https
    header_upstream X-Forwarded-Ssl on
    header_upstream X-Url-Scheme https
}
proxy /services/openmaptiles localhost:8000 {
    header_downstream Cache-Control "public, max-age=20000, stale-while-revalidate=1000"
    transparent
    header_upstream X-Forwarded-Proto https
    header_upstream X-Forwarded-Ssl on
    header_upstream X-Url-Scheme https
}
```

With the above the TileJSONs serve `https` urls.
